api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "voyager-miles-discount"

uid = "f596eb97-6a95-b0ee-a992-f58f8d5d6b8beb5aaff1"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "input.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
